# Generated by Django 4.0.4 on 2022-05-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=30)),
                ('slot1', models.IntegerField()),
                ('slot2', models.IntegerField()),
                ('slot3', models.IntegerField()),
                ('slot4', models.IntegerField()),
                ('slot5', models.IntegerField()),
                ('slot6', models.IntegerField()),
                ('slot7', models.IntegerField()),
                ('teacher_mail', models.CharField(max_length=55)),
            ],
        ),
    ]
