# Generated by Django 4.0.4 on 2022-05-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timebale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='dept_name',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
