# Generated by Django 4.0.4 on 2022-05-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timebale', '0002_timetable_dept_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='dept_name',
            field=models.CharField(max_length=5),
        ),
    ]
